AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template for RDS: Create
  an Amazon RDS instance
Parameters:
  VPCStackName:
    Description: Name of the stack used for VPC
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "VPCStack"
  RegionName:
    Description: Name of the region
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
  RDSInstanceType:
    Description: Type of RDS instance
    Type: String
    Default: db.t2.micro
    AllowedValues:
        - db.t2.micro
        - db.t2.small
        - db.t2.medium
        - db.t2.large
        - db.t2.xlarge
        - db.r5.small
        - db.r5.medium
        - db.r5.large
        - db.r5.xlarge
Mappings:
  AZNames:
    us-east-1:
      a: us-east-1a
      b: us-east-1b
      c: us-east-1c
    us-east-2:
      a: us-east-2a
      b: us-east-2b
      c: us-east-2c
    us-west-1:
      a: us-west-1a
      b: us-west-1b
      c: us-west-1c
    us-west-2:
      a: us-west-2a
      b: us-west-2b
      c: us-west-2c
    eu-west-1:
      a: us-west-1
      b: us-west-1
      c: us-west-1
Resources:
  DBSubnetGroupDEV:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet Group for DEV environment
      DBSubnetGroupName: SubnetGroupDEV
      SubnetIds:
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnet01Id"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnet02Id"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnet01Id"
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !Ref RDSInstanceType
      DBInstanceIdentifier: djangodev
      DBName: djangodev
      MasterUsername: db_django
      MasterUserPassword: r1t3Tf83!
      Engine: postgres
      EngineVersion: "11.5"
      PubliclyAccessible: true
      MultiAZ: false
      DBSubnetGroupName: !Ref DBSubnetGroupDEV
      AllocatedStorage: 20
      StorageType: standard
Outputs:
  RDSHost:
    Description: Host name of the RDS
    Value: !GetAtt RDS.Endpoint.Address
    Export :
      Name : !Sub "${AWS::StackName}-RDSHost"
  RDSId:
    Description: InstanceId of the newly created RDS Instance
    Value: !Ref RDS
    Export:
      Name: !Sub "${AWS::StackName}-RDSId"